accessing
allSmalltalkImages
	"See #glAsSmalltalkImagesStoreString re how this list was created"
		
	^ #('GemStone-3.1.0.6' 'GemStone-3.2.12' 'GemStone-3.3.0' 'Moose-6.0' 'Moose-6.1' 'Moose-trunk' 'Pharo-3.0' 'Pharo-4.0' 'Pharo-5.0' 'Pharo-6.0' 'Pharo-6.1' 'Pharo-7.0' 'Pharo-alpha' 'Pharo-stable' 'Pharo64-6.0' 'Pharo64-6.1' 'Pharo64-7.0' 'Pharo64-alpha' 'Pharo64-stable' 'Squeak-4.5' 'Squeak-4.6' 'Squeak-5.0' 'Squeak-5.1' 'Squeak-trunk' )